# Generated by Django 5.0.3 on 2024-04-16 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='postDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='postDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='postDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
