# Generated by Django 5.0.3 on 2024-04-23 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awtapp', '0002_alter_answer_content_alter_answer_postdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='questionId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='answer',
            new_name='answerId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='questionId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='questiontag',
            old_name='question',
            new_name='questionId',
        ),
        migrations.AlterUniqueTogether(
            name='questiontag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='userId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='awtapp.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='hashedPassword',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='joinDate',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='AnswerDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.answer')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.answer')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDislikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.question')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.question')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.user')),
            ],
        ),
        migrations.AddConstraint(
            model_name='answerdislikes',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_ad'),
        ),
        migrations.AddConstraint(
            model_name='answerlikes',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_al'),
        ),
        migrations.AddConstraint(
            model_name='questiondislikes',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_qd'),
        ),
        migrations.AddConstraint(
            model_name='questionlikes',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_ql'),
        ),
    ]
