# Generated by Django 5.0.3 on 2024-05-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awtapp', '0003_remove_answerdislike_unique_key_pair_ad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user_id',
            new_name='user',
        ),
    ]
