# Generated by Django 5.0.3 on 2024-04-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awtapp', '0003_rename_question_answer_questionid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionLikes',
            new_name='AnswerDislike',
        ),
        migrations.RenameModel(
            old_name='AnswerDislikes',
            new_name='AnswerLike',
        ),
        migrations.RenameModel(
            old_name='AnswerLikes',
            new_name='QuestionDislike',
        ),
        migrations.RenameModel(
            old_name='QuestionDislikes',
            new_name='QuestionLike',
        ),
        migrations.RemoveConstraint(
            model_name='answerdislike',
            name='unique_key_pair_ql',
        ),
        migrations.RemoveConstraint(
            model_name='answerlike',
            name='unique_key_pair_ad',
        ),
        migrations.RemoveConstraint(
            model_name='questiondislike',
            name='unique_key_pair_al',
        ),
        migrations.RemoveConstraint(
            model_name='questionlike',
            name='unique_key_pair_qd',
        ),
        migrations.AlterField(
            model_name='answerdislike',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.answer'),
        ),
        migrations.AlterField(
            model_name='questiondislike',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awtapp.question'),
        ),
        migrations.AddConstraint(
            model_name='answerdislike',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_ad'),
        ),
        migrations.AddConstraint(
            model_name='answerlike',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_al'),
        ),
        migrations.AddConstraint(
            model_name='questiondislike',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_qd'),
        ),
        migrations.AddConstraint(
            model_name='questionlike',
            constraint=models.UniqueConstraint(fields=('questionId', 'userId'), name='unique_key_pair_ql'),
        ),
    ]
