# Generated by Django 5.0.3 on 2024-05-14 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awtapp', '0004_rename_user_id_question_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='answerdislike',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answerdislike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questiondislike',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questiondislike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questiontag',
            old_name='question_id',
            new_name='question',
        ),
    ]
