# Generated by Django 5.0.3 on 2024-04-23 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awtapp', '0005_rename_user_userprofile_remove_question_userid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answerdislike',
            name='unique_key_pair_ad',
        ),
        migrations.RemoveConstraint(
            model_name='answerlike',
            name='unique_key_pair_al',
        ),
        migrations.RemoveConstraint(
            model_name='questiondislike',
            name='unique_key_pair_qd',
        ),
        migrations.RemoveConstraint(
            model_name='questionlike',
            name='unique_key_pair_ql',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answerdislike',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answerdislike',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answerlike',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='answerId',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questiondislike',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questiondislike',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questionlike',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='questiontag',
            old_name='questionId',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userId',
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='answerdislike',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_key_pair_ad'),
        ),
        migrations.AddConstraint(
            model_name='answerlike',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_key_pair_al'),
        ),
        migrations.AddConstraint(
            model_name='questiondislike',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_key_pair_qd'),
        ),
        migrations.AddConstraint(
            model_name='questionlike',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_key_pair_ql'),
        ),
    ]
